### ISSUE TITLE
Possible refactor of enum variants

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/sn_transfers#34]
https://github.com/maidsafe/safe-transfers/blob/5960b53ac23278552b9c30911021233c770895f3/src/lib.rs#L112-L126

Going through the vault code I identified that we have enum variants which hold structs of the same name. Is there any particular reason this is designed this way? Could we replace is with a something like:
```
enum ActorEvent {
     TransferInitiated {
          // required fields
     }
     ...
}
```
This would reduce the number of structs in the public API. Any thoughts?

**Comment by S-Coyle** [comment]
Closing this as it's almost a year old and this repo is being archived - can be recreated in [safe_network](https://github.com/maidsafe/safe_network) if still relevant
